# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: regionbook.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='regionbook.proto',
  package='threeregion',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10regionbook.proto\x12\x0bthreeregion\"\xfc\x01\n\x06Region\x12\n\n\x02id\x18\x01 \x02(\t\x12\x10\n\x08\x66ullname\x18\x02 \x02(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\x05\x12\x30\n\x08location\x18\x05 \x01(\x0b\x32\x1e.threeregion.Region.Coordinate\x12(\n\x04\x63idx\x18\x06 \x01(\x0b\x32\x1a.threeregion.Region.Cindex\x12\r\n\x05\x61lias\x18\x07 \x03(\t\x1a&\n\nCoordinate\x12\x0b\n\x03lat\x18\x01 \x02(\x01\x12\x0b\n\x03lng\x18\x02 \x02(\x01\x1a$\n\x06\x43index\x12\r\n\x05start\x18\x01 \x02(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x02(\x05\"2\n\nRegionBook\x12$\n\x07\x61\x64\x64ress\x18\x01 \x03(\x0b\x32\x13.threeregion.Region\"\x8a\x01\n\x0bLevelRegion\x12)\n\x08province\x18\x01 \x01(\x0b\x32\x17.threeregion.RegionBook\x12%\n\x04\x63ity\x18\x02 \x01(\x0b\x32\x17.threeregion.RegionBook\x12)\n\x08\x64istrict\x18\x03 \x01(\x0b\x32\x17.threeregion.RegionBook')
)




_REGION_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='threeregion.Region.Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat', full_name='threeregion.Region.Coordinate.lat', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng', full_name='threeregion.Region.Coordinate.lng', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=248,
)

_REGION_CINDEX = _descriptor.Descriptor(
  name='Cindex',
  full_name='threeregion.Region.Cindex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='threeregion.Region.Cindex.start', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='threeregion.Region.Cindex.end', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=286,
)

_REGION = _descriptor.Descriptor(
  name='Region',
  full_name='threeregion.Region',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='threeregion.Region.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fullname', full_name='threeregion.Region.fullname', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='threeregion.Region.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='threeregion.Region.level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='threeregion.Region.location', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cidx', full_name='threeregion.Region.cidx', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alias', full_name='threeregion.Region.alias', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REGION_COORDINATE, _REGION_CINDEX, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=286,
)


_REGIONBOOK = _descriptor.Descriptor(
  name='RegionBook',
  full_name='threeregion.RegionBook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='threeregion.RegionBook.address', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=338,
)


_LEVELREGION = _descriptor.Descriptor(
  name='LevelRegion',
  full_name='threeregion.LevelRegion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='province', full_name='threeregion.LevelRegion.province', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='threeregion.LevelRegion.city', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='district', full_name='threeregion.LevelRegion.district', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=479,
)

_REGION_COORDINATE.containing_type = _REGION
_REGION_CINDEX.containing_type = _REGION
_REGION.fields_by_name['location'].message_type = _REGION_COORDINATE
_REGION.fields_by_name['cidx'].message_type = _REGION_CINDEX
_REGIONBOOK.fields_by_name['address'].message_type = _REGION
_LEVELREGION.fields_by_name['province'].message_type = _REGIONBOOK
_LEVELREGION.fields_by_name['city'].message_type = _REGIONBOOK
_LEVELREGION.fields_by_name['district'].message_type = _REGIONBOOK
DESCRIPTOR.message_types_by_name['Region'] = _REGION
DESCRIPTOR.message_types_by_name['RegionBook'] = _REGIONBOOK
DESCRIPTOR.message_types_by_name['LevelRegion'] = _LEVELREGION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Region = _reflection.GeneratedProtocolMessageType('Region', (_message.Message,), {

  'Coordinate' : _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), {
    'DESCRIPTOR' : _REGION_COORDINATE,
    '__module__' : 'regionbook_pb2'
    # @@protoc_insertion_point(class_scope:threeregion.Region.Coordinate)
    })
  ,

  'Cindex' : _reflection.GeneratedProtocolMessageType('Cindex', (_message.Message,), {
    'DESCRIPTOR' : _REGION_CINDEX,
    '__module__' : 'regionbook_pb2'
    # @@protoc_insertion_point(class_scope:threeregion.Region.Cindex)
    })
  ,
  'DESCRIPTOR' : _REGION,
  '__module__' : 'regionbook_pb2'
  # @@protoc_insertion_point(class_scope:threeregion.Region)
  })
_sym_db.RegisterMessage(Region)
_sym_db.RegisterMessage(Region.Coordinate)
_sym_db.RegisterMessage(Region.Cindex)

RegionBook = _reflection.GeneratedProtocolMessageType('RegionBook', (_message.Message,), {
  'DESCRIPTOR' : _REGIONBOOK,
  '__module__' : 'regionbook_pb2'
  # @@protoc_insertion_point(class_scope:threeregion.RegionBook)
  })
_sym_db.RegisterMessage(RegionBook)

LevelRegion = _reflection.GeneratedProtocolMessageType('LevelRegion', (_message.Message,), {
  'DESCRIPTOR' : _LEVELREGION,
  '__module__' : 'regionbook_pb2'
  # @@protoc_insertion_point(class_scope:threeregion.LevelRegion)
  })
_sym_db.RegisterMessage(LevelRegion)


# @@protoc_insertion_point(module_scope)
